### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [qhzhyt/http-git-server#1]
Hi,
Thank you for releasing this awesome project!
May I ask what the license is?
Thank you!

**Comment by qhzhyt** [comment]
This is a demo for git http server, you can freely modify and use it if you want.

**Comment by fakerybakery** [comment]
Thanks! Does this mean it is CC0 licensed?

**Comment by qhzhyt** [comment]
> Thanks! Does this mean it is CC0 licensed?

Yes

**Comment by fakerybakery** [comment]
Thank you! Opened #2 for clarity
